---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC BY 3.0. All rights reserved.
#
#
# Role Lynis
#
# Clean DNF
- name: Clean DNF before install Lynis
  ansible.builtin.command: dnf clean all
  tags:
    - lynis

# Add Repository Lynis
- name: Verify if Lynis Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/lynis-chrome.repo
  register: lynisrepo
  tags:
    - repolynis
    - lynis

- name: Adding Lynis Repository
  ansible.builtin.yum_repository:
    name: lynis
    description: Lynis
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    enabled: true
    gpgcheck: true
  when: lynisrepo.stat.exists == False
  tags:
    - repolynis
    - lynis

# Install Software
- name: Install Lynis
  ansible.builtin.dnf:
    name:
      - lynis                         # Security Tool - Very interesting
    state: present
  tags:
    - lynis
