---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# Role Google-Chrome
#
# Clean DNF
- name: Clean DNF before install Google-Chrome
  ansible.builtin.command: dnf clean all
  tags:
    - chrome

# Add Repository Google Chrome
- name: Verify if Google Chrome Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/google-chrome.repo
  register: googlechromerepo
  tags:
    - repochrome
    - chrome

- name: Adding Google Chrome Repository
  ansible.builtin.yum_repository:
    name: google-chrome
    description: Google-Chrome
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  when: googlechromerepo.stat.exists == False
  tags:
    - repochrome
    - chrome

# Install Software
- name: Install Google-Chrome
  ansible.builtin.dnf:
    name:
      - google-chrome-stable          # Google Chrome browser
    state: present
  tags:
    - chrome
