- hosts: localhost
  remote_user : root
  roles:
      - bootstrap
      - packagekit
      - softwares
      - atom-editor
      - basiccodecs
      - ssd-drive
      - hb-and-mkmkv-needed-softwares
      - handbrake
      - makemkv

  vars_files:
    - myvars.yml
