---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
- name: Post install my Fedora System
  hosts: localhost
  become: true
  become_method: sudo
  roles:
    - bootstrap
    - disable-ipv6
    - softwares
    - google-chrome
    - lynis
    - vscode
    - hb-and-mkmkv-needed-softwares
    - handbrake
    - makemkv
    - podman
    # - libdvdcss
    # - remove-softwares
    # - rescue-boot
    # - disable-webcam
    # - virtualbox

  vars_files:
    - myvars.yml
