---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#
- hosts: localhost
  remote_user : root
  roles:
      - bootstrap
      - disable-ipv6
      - softwares
      - asbru-cm
      - hb-and-mkmkv-needed-softwares
      - handbrake
      - makemkv
      #- libdvdcss
      #- rescue-boot
      #- disable-webcam
      #- remove-softwares

  vars_files:
    - myvars.yml
