- hosts: localhost
  remote_user : root
  roles:
      - bootstrap
      - softwares
      #- bumblebee # NOK witk Wayland but worked with X11
      - basiccodecs
      - hb-and-mkmkv-needed-softwares
      - handbrake
      - makemkv

  vars_files:
    - myvars.yml
