---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# tasks file for ssd-drive

# Verify if RC.Local exist
- name: Verify if RC.Local exist
  stat: path=/etc/rc.d/rc.local
  register: rclocal
  tags:
    rccnf

# Create RC.Local
- name: Create RC.Local
  command: touch /etc/rc.d/rc.local
  tags:
    rccnf

# Change Access Rights
- file: path=/etc/rc.d/rc.local mode=0777 owner=root group=root
  tags:
    rccnf

# Insert Scheduler for SSD Drive
- name: Prepare RC.Local
  lineinfile: dest=/etc/rc.d/rc.local line="#!/bin/bash"
  when: rclocal.stat.exists == False
  tags:
    rccnf

# Insert Scheduler for SSD Drive
- name: Insert Scheduler for SSD Drive on /dev/sda in RC.local
  lineinfile: dest=/etc/rc.d/rc.local line="echo 'deadline' > /sys/block/sda/queue/scheduler"
  tags:
    rccnf

# Create RC.Local.Service
- name: Create RC.Local
  template: src=templates/rc-local.service.tpl dest=/etc/systemd/system/rc-local.service mode=0777 owner=root group=root
  when: rclocal.stat.exists == False
  tags:
    rccnf

# Enable RC.Local.Service
- name: Enable RC.Local.Service
  systemd: name=rc-local.service enabled=true
  tags:
    rccnf

# Start RC.Local.Service
- name: Start RC.Local.Service
  systemd: name=rc-local.service state=started
  when: rclocal.stat.exists == False
  tags:
    rccnf

# Enable TRIM Service
- name: Enable TRIM Service
  systemd: name=fstrim.timer enabled=true
  tags:
    enabtrim

# Enable SSD in LVM Configuration
- replace:
    path: /etc/lvm/lvm.conf
    regexp: "issue_discards = 0"
    replace: "issue_discards = 1"
    #backup: yes
  tags:
    enabtrim

# Disable Swap disk activity
- name: Disable Swap disk activity
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = 0"
