---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# Role VSCode
#
# Clean DNF
- name: Clean DNF before install VSCode
  ansible.builtin.shell: 
    cmd: dnf clean all
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/bin:/sbin"
  tags:
    - vscode

# Add Repository VScode
- name: Verify if VScode Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/vscode.repo
  register: vscoderepo
  tags:
    - repovscode
    - vscode

- name: VScode enable Repository
  ansible.builtin.yum_repository:
    name: vscode
    description: VSCode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true
    gpgcheck: true
  when: vscoderepo.stat.exists == False
  tags:
    - repovscode
    - vscode

# Install Software
- name: Install VSCode
  ansible.builtin.dnf:
    name:
      - code                          # Visual Studio Code
    state: present
  tags:
    - vscode
