---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# Role Disable Webcam
#
# Add Blacklist file to disable Webcam
- name: Test blacklist file
  ansible.builtin.stat:
    path: /etc/modprobe.d/blacklist.conf
  register: blacklistfile
  tags:
    - blacklistf
    - disablewebcam

- name: Disable Webcam - blacklist file do not exist
  ansible.builtin.file: 
    path: /etc/modprobe.d/blacklist.conf 
    state: touch
    mode: '0644'
    owner: root
    group: root
  when: blacklistfile.stat.exists == False
  tags:
    - blacklistf
    - disablewebcam

- name: Disable Webcam - blacklist file exist - comment
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf 
    line: '# Disable Webcam on linux'
  tags:
    - blacklistf
    - disablewebcam

- name: Disable Webcam - blacklist file exist - blacklist module
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf 
    line: 'blacklist uvcvideo'
  tags:
    - blacklistf
    - disablewebcam