---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# Role Disable Webcam

# Add Blacklist file to disable Webcam
- name: Test blacklist file
  stat: path=/etc/modprobe.d/blacklist.conf
  register: blacklistfile
  tags:
    - blacklistf
    - basicinst

- name: Disable Webcam - blacklist file do not exist
  ansible.builtin.file: 
    path: /etc/modprobe.d/blacklist.conf 
    state: touch
    mode: 0644
    owner: root
    group: root
  when: blacklistfile.stat.exists == False
  tags:
    - blacklistf
    - basicinst

- name: Disable Webcam - blacklist file exist - comment
  lineinfile: dest=/etc/modprobe.d/blacklist.conf line="# Disable Webcam on linux"
  tags:
    - blacklistf
    - basicinst

- name: Disable Webcam - blacklist file exist - blacklist module
  lineinfile: dest=/etc/modprobe.d/blacklist.conf line="blacklist uvcvideo"
  tags:
    - blacklistf
    - basicinst