---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# tasks file for atom-editor
# Role Atom-Editor

# Add Atom-Editor
- name: Verify if Atom-Editor exist
  stat: path=/usr/bin/atom
  register: atomeditor
  tags:
    - atom

# Download lastest version Atom-Editor
- name: Download lastest version Atom-Editor
  command: "wget -O /tmp/atom.x86_64.rpm http://atom.io/download/rpm"
  when: atomeditor.stat.exists == False
  tags:
    - atom

- name: Install Atom-Editor
  shell: rpm -Uhv /tmp/atom.x86_64.rpm
  when: atomeditor.stat.exists == False
  tags:
    - atom

# Clean Mplayer Codecs
- name: Delete Atom-Editor File
  file:
    path: "/tmp/atom.x86_64.rpm"
    state: absent
  when: atomeditor.stat.exists == False
  tags:
    - atom
