---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# tasks file for handbrake

# Handbrake Compilation
# https://handbrake.fr/docs/en/latest/developer/build-linux.html

# Check Handbrake exist
- name: Verify if Handbrake exist
  stat: path=/usr/local/bin/HandBrakeCLI
  register: handbrakeexist
  tags:
    - minhbmk
    - handbk

# Create Folder to Compile
- name: Create Folder to Compile
  file:
    path: "/tmp/Handbrake-Build"
    state: directory
    mode: 0775
  when: handbrakeexist.stat.exists == False
  tags:
    - minhbmk
    - handbk

# Download lastet version on Git Repository
- name: Downloading HandBrake from github...
  shell: 'cd /tmp/Handbrake-Build/ && git clone https://github.com/HandBrake/HandBrake.git'
  when: handbrakeexist.stat.exists == False
  tags:
    - minhbmk
    - handbk

# Compile Handbrake
- name: configure make install
  shell: 'cd /tmp/Handbrake-Build/HandBrake && ./configure --launch-jobs=$(nproc) --launch'
  when: handbrakeexist.stat.exists == False
  tags:
    - minhbmk
    - handbk

- make:
    chdir: "/tmp/Handbrake-Build/HandBrake/build"
    target: install
  when: handbrakeexist.stat.exists == False
  tags:
    - minhbmk
    - handbk

# Clean Handbrake-Build
- name: Delete Handbrake-Build Folder
  file:
    path: "/tmp/Handbrake-Build"
    state: absent
  when: handbrakeexist.stat.exists == False
  tags:
    - minhbmk
    - handbk
