---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# tasks file for handbrake
#
# Handbrake Compilation
# https://handbrake.fr/docs/en/latest/developer/build-linux.html

# Check Handbrake exist
- name: Verify if Handbrake exist
  ansible.builtin.stat:
    path: /usr/local/bin/HandBrakeCLI
  register: handbrakeexist
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk

# Create Folder to Compile
- name: Create Folder to Compile
  ansible.builtin.file:
    path: "/tmp/Handbrake-Build"
    state: directory
    mode: '0775'
  when: handbrakeexist.stat.exists == False
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk

# Download lastet version on Git Repository
- name: Downloading HandBrake from github...
  ansible.builtin.shell:
    cmd: cd /tmp/Handbrake-Build/ && git clone https://github.com/HandBrake/HandBrake.git
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/bin:/sbin"
  when: handbrakeexist.stat.exists == False
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk

# Compile Handbrake
- name: Configure   Make   Make Install
  ansible.builtin.shell:
    cmd: cd /tmp/Handbrake-Build/HandBrake && ./configure --launch-jobs=$(nproc) --launch
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/bin:/sbin"
  when: handbrakeexist.stat.exists == False
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk

- name: Make Install
  community.general.make:
    chdir: "/tmp/Handbrake-Build/HandBrake/build"
    target: install
  when: handbrakeexist.stat.exists == False
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk

# Clean Handbrake-Build
- name: Delete Handbrake-Build Folder
  ansible.builtin.file:
    path: "/tmp/Handbrake-Build"
    state: absent
  when: handbrakeexist.stat.exists == False
  tags:
    - mixhbmk
    - handbk
    - onlyhandbk
