---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC BY 3.0. All rights reserved.
#

# Role Disable IPv6

# Disable IPv6 - 3 lines to disable it
- name: Disable IPv6 -a
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
        net.ipv6.conf.all.disable_ipv6 = 1
        net.ipv6.conf.default.disable_ipv6 = 1
        net.ipv6.conf.lo.disable_ipv6 = 1
  tags:
    - ipv6
    - basicinst

# Disable ::1 ipv6 localhost in /etc/hosts
# Lines to comment in hosts file
- name: Disable ::1 ipv6 localhost on /etc/hosts
  ansible.builtin.replace:
     path: /etc/hosts
     regexp: '^::1'
     replace: '#::1'
     backup: true
  tags:
    - ipv6
    - basicinst

# Disable ipv6 in /etc/default/grub
# Modify grub
- name: Disable ipv6 in /etc/default/grub
  ansible.builtin.replace:
     path: /etc/default/grub
     regexp: 'quiet'
     replace: 'ipv6.disable=1 quiet'
     backup: true
  tags:
    - ipv6
    - basicinst

# Deploy new grub setting
- name: Run grub2-mkconfig to update /boot/grub/grub.cfg
  ansible.builtin.command:
    cmd: grub2-mkconfig
  tags:
    - ipv6
    - basicinst
