---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# Role Disable IPv6
#

# Not needed anymore with recent Fedora Version ###############
#
# Disable IPv6 - 3 lines to disable it 
#- name: Disable IPv6
#  ansible.builtin.blockinfile:
#    path: /etc/sysctl.conf
#    block: |
#        net.ipv6.conf.all.disable_ipv6 = 1
#        net.ipv6.conf.default.disable_ipv6 = 1
#        net.ipv6.conf.lo.disable_ipv6 = 1
#  tags:
#    - ipv6
#    - basicinst
# Not needed anymore with recent Fedora Version ###############

# Remove previous syntaxe to disable IPv6 from /etc/sysctl.conf
# Modify sysctl.conf
- name: Remove previous syntax to disable IPv6 from /etc/sysctl.conf (first line)
  ansible.builtin.lineinfile:
     path: /etc/sysctl.conf
     state: absent
     regexp: 'net.ipv6.conf.all.disable_ipv6 = 1'
     backup: true
  tags:
    - ipv6
    - basicinst

- name: Remove previous syntax to disable IPv6 from /etc/sysctl.conf (second line)
  ansible.builtin.lineinfile:
     path: /etc/sysctl.conf
     state: absent
     regexp: 'net.ipv6.conf.default.disable_ipv6 = 1'
  tags:
    - ipv6
    - basicinst

- name: Remove previous syntax to disable IPv6 from /etc/sysctl.conf (last line)
  ansible.builtin.lineinfile:
     path: /etc/sysctl.conf
     state: absent
     regexp: 'net.ipv6.conf.lo.disable_ipv6 = 1'
  tags:
    - ipv6
    - basicinst

# Disable ::1 ipv6 localhost from /etc/hosts
# Lines to comment in hosts file
- name: Disable IPv6 localhost from /etc/hosts
  ansible.builtin.replace:
     path: /etc/hosts
     regexp: '^::1'
     replace: '#::1'
     backup: true
  tags:
    - ipv6
    - basicinst

# Disable ipv6 from /etc/default/grub
# Modify grub
- name: Disable IPv6 from Grub
  ansible.builtin.replace:
     path: /etc/default/grub
     regexp: 'rhgb quiet'
     replace: 'rhgb ipv6.disable=1 quiet'
     backup: true
  tags:
    - ipv6
    - basicinst

# Deploy new grub setting
- name: Run grub2-mkconfig to update /boot/grub2/grub.cfg
  ansible.builtin.shell:
    cmd: grub2-mkconfig
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/bin:/sbin"
  tags:
    - ipv6
    - basicinst
