---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# tasks file for roles/asbru-cm
#
- name: Verify if Asbru-CM exist
  ansible.builtin.stat:
    path: /usr/bin/asbru-cm
  register: asbru
  tags:
    - asbru

- name: Download Asbru-CM
  ansible.builtin.shell: 
     cmd: "wget -O /tmp/asbru-cm.rpm {{ Asbru_Url_Version }}"
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/bin:/usr/sbin:/bin:/sbin:{{ ansible_env.PATH }}"
  when: asbru.stat.exists == False
  tags:
    - asbru

- name: Install Asbru-CM
  ansible.builtin.dnf:
    name: /tmp/asbru-cm.rpm
    state: present
    disable_gpg_check: true
  when: asbru.stat.exists == False
  tags:
    - asbru

# Clean Asbru-CM download
- name: Delete Asbru-CM temporary downloaded file
  ansible.builtin.file:
    path: "/tmp/asbru-cm.rpm"
    state: absent
  when: asbru.stat.exists == False
  tags:
    - asbru
