---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC-BY-NC-SA 3.0. All rights reserved.
#
#
# Role VirtualBox
#
# Add Repository Oracle VirtualBox
- name: Verify if Oracle VirtualBox Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/virtualbox.repo
  register: repooraclevbox
  tags:
    - repooraclevbox
    - virtualbox

- name: Adding Oracle VirtualBox Repository
  ansible.builtin.yum_repository:
    name: virtualbox
    description: Virtualbox
    #baseurl: https://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    # Fedora 36 is the maximum released version for now
    baseurl: https://download.virtualbox.org/virtualbox/rpm/fedora/36/x86_64/
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  when: repooraclevbox.stat.exists == False
  tags:
    - repooraclevbox
    - virtualbox

# Clean DNF
- name: Clean DNF before Install VirtualBox
  ansible.builtin.shell: 
    cmd: dnf clean all
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/bin:/sbin"
  tags:
    - repooraclevbox
    - virtualbox

# Install Default Softwares
- name: Install VirtualBox Packages
  ansible.builtin.dnf:
    name:
      - VirtualBox                   # Virtualization software
      - virtualbox-guest-additions   # Virtualization software tools and guest drivers.
    state: present
  tags:
    - virtualbox
