---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# tasks file for makemkv

# MakeMKV Compilation
# https://linuxconfig.org/how-to-install-makemkv-on-fedora-linux

# Check MakeMKV exist
#- name: Verify if MakeMKV exist
#  stat: path=/usr/bin/makemkv
#  register: makemkvexist
#  tags:
#    mkmkv

# Exit if exist
#- meta: end_play
#  when: makemkvexist.stat.exists
#  tags:
#    mkmkv

# Create Folder to Compile
- name: Create Folder to Compile
  file:
     path: "/tmp/MakeMKV"
     state: directory
     mode: 0775
  tags:
    mkmkv

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV OSS
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_OSS }}.tar.gz
     dest: "/tmp/MakeMKV"
     mode: 0644
  tags:
    mkmkv

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV BIN
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_BIN }}.tar.gz
     dest: "/tmp/MakeMKV"
     mode: 0644
  tags:
    mkmkv

# Uncompress BIN Files
- name: Uncompress BIN Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_BIN }}.tar.gz"
     dest: "/tmp/MakeMKV"
  tags:
    mkmkv

# Uncompress OSS Files
- name: Uncompress OSS Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_OSS }}.tar.gz"
     dest: "/tmp/MakeMKV"
  tags:
    mkmkv

# Patch before Compile MakeMKV_OSS
#- name: Patch OSS Files
#  shell: patch /tmp/MakeMKV/{{ MakeMKV_OSS }}/libffabi/src/ffabi.c < patch.file

# Compile MakeMKV OSS
- name: configure
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && ./configure'
  tags:
    mkmkv

- name: Compile MakeMKV OSS
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && echo -e "\nq\nyes" | make'
  args:
     executable: /bin/bash
  tags:
    mkmkv

- make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_OSS }}"
     target: install
  tags:
    mkmkv

# Compile MakeMKV BIN
- name: Create Folder BIN to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp"
     state: directory
     mode: 0775
  tags:
    mkmkv

- name: Create File to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp/eula_accepted"
     state: touch
     mode: 0775
  tags:
    mkmkv

- name: Compile MakeMKV BIN
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_BIN }} &&  make'
  args:
     executable: /bin/bash
  tags:
    mkmkv

- make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_BIN }}"
     target: install
  tags:
    mkmkv

# Clean MakeMKV-Build
- name: Delete MakeMKV Folder
  file:
     path: "/tmp/MakeMKV"
     state: absent
  tags:
    mkmkv
