---
# tasks file for makemkv

# MakeMKV Compilation
# https://linuxconfig.org/how-to-install-makemkv-on-fedora-linux

# Check MakeMKV exist
- name: Verify if MakeMKV exist
  stat: path=/usr/bin/makemkv
  register: makemkvexist

# Exit if exist
- meta: end_play
  when: makemkvexist.stat.exists

# Create Folder to Compile
- name: Create Folder to Compile
  file:
     path: "/tmp/MakeMKV"
     state: directory
     mode: 0775

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV OSS
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_version_OSS }}
     dest: "/tmp/MakeMKV"
     mode: 0644

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV BIN
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_version_BIN }}
     dest: "/tmp/MakeMKV"
     mode: 0644

# Uncompress BIN Files
- name: Uncompress BIN Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_BIN }}.tar.gz"
     dest: "/tmp/MakeMKV"

# Uncompress OSS Files
- name: Uncompress OSS Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_OSS }}.tar.gz"
     dest: "/tmp/MakeMKV"

# Compile MakeMKV OSS
- name: configure
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && ./configure'

- name: Compile MakeMKV OSS
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && echo -e "\nq\nyes" | make'
  args:
     executable: /bin/bash

- make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_OSS }}"
     target: install

# Compile MakeMKV BIN
- name: Create Folder BIN to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp"
     state: directory
     mode: 0775

- name: Create File to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp/eula_accepted"
     state: touch
     mode: 0775

- name: Compile MakeMKV BIN
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_BIN }} &&  make'
  args:
     executable: /bin/bash

- make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_BIN }}"
     target: install

# Clean MakeMKV-Build
- name: Delete MakeMKV Folder
  file:
     path: "/tmp/MakeMKV"
     state: absent
