---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# Role MakeMKV

# MakeMKV Compilation
# https://linuxconfig.org/how-to-install-makemkv-on-fedora-linux

# Check MakeMKV exist
- name: Verify if MakeMKV exist
  stat: path=/usr/bin/makemkv
  register: makemkvexist
  tags:
    - mkmkv
    - minhbmk

# Create Folder to Compile
- name: Create Folder to Compile
  file:
     path: "/tmp/MakeMKV"
     state: directory
     mode: 0775
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV OSS
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_OSS }}.tar.gz
     dest: "/tmp/MakeMKV"
     mode: 0644
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Download lastest version on www.makemkv.com
- name: Downloading MakeMKV BIN
  get_url:
     url: http://www.makemkv.com/download/{{ MakeMKV_BIN }}.tar.gz
     dest: "/tmp/MakeMKV"
     mode: 0644
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Uncompress BIN Files
- name: Uncompress BIN Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_BIN }}.tar.gz"
     dest: "/tmp/MakeMKV"
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Uncompress OSS Files
- name: Uncompress OSS Achive
  unarchive:
     src: "/tmp/MakeMKV/{{ MakeMKV_OSS }}.tar.gz"
     dest: "/tmp/MakeMKV"
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Compile MakeMKV OSS
- name: Configure
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && ./configure'
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

- name: Compile MakeMKV OSS
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_OSS }} && echo -e "\nq\nyes" | make'
  args:
     executable: /bin/bash
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

- name: Make Install
  make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_OSS }}"
     target: install
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Compile MakeMKV BIN
- name: Create Folder BIN to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp"
     state: directory
     mode: 0775
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

- name: Create File to Compile
  file:
     path: "/tmp/MakeMKV/{{ MakeMKV_BIN }}/tmp/eula_accepted"
     state: touch
     mode: 0775
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

- name: Compile MakeMKV BIN
  shell: 'cd /tmp/MakeMKV/{{ MakeMKV_BIN }} &&  make'
  args:
     executable: /bin/bash
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

- name: Make Install
  make:
     chdir: "/tmp/MakeMKV/{{ MakeMKV_BIN }}"
     target: install
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Clean MakeMKV-Build
- name: Delete MakeMKV Folder
  file:
     path: "/tmp/MakeMKV"
     state: absent
  when: makemkvexist.stat.exists == False
  tags:
    - mkmkv
    - minhbmk

# Create Symbolic Link for VLC
- name: Create Symbolic Link for VLC - libaacs
  ansible.builtin.file:
    src: /usr/lib64/libmmbd.so.0
    dest: /usr/lib64/libaacs.so.0
    owner: root
    group: root
    state: link
  tags:
    - mkmkv
    - minhbmk
    - symlinkvlc

# Create Symbolic Link for VLC
- name: Create Symbolic Link for VLC - libaacs
  ansible.builtin.file:
    src: /usr/lib64/libmmbd.so.0
    dest: /usr/lib64/libbdplus.so.0
    owner: root
    group: root
    state: link
  tags:
    - mkmkv
    - minhbmk
    - symlinkvlc