---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC BY 3.0. All rights reserved.
#
#
# Role libdvdcss
#
# Add Repository RPM Fusion Tainted only to install libdvdcss
- name: Verify if RPM Fusion Tainted Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-tainted.repo
  register: taintedrepo
  tags:
    - libdvdcss
    - basicinst

- name: Adding RPM Fusion Tainted Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree-tainted
    description: rpmfusion-nonfree-tainted
    file: rpmfusion-nonfree-tainted
    baseurl: #blablabla
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-tainted-$releasever&arch=$basearch
    enabled: true
    gpgcheck: true
    repo_gpgcheck: false
    failovermethod: roundrobin
  when: taintedrepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Adding RPM Fusion Tainted-Debug Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree-tainted-debug
    description: rpmfusion-nonfree-tainted-Debug
    file: rpmfusion-nonfree-tainted    
    baseurl: #blablabla
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-tainted-debug-$releasever&arch=$basearch
    enabled: false
    gpgcheck: true
    repo_gpgcheck: false
    failovermethod: roundrobin
  when: taintedrepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Adding RPM Fusion Tainted-Source Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree-tainted-Source
    description: rpmfusion-nonfree-tainted-Source
    file: rpmfusion-nonfree-tainted    
    baseurl: #blablabla
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-tainted-source-$releasever&arch=$basearch
    enabled: false
    gpgcheck: true
    repo_gpgcheck: false
    failovermethod: roundrobin
  when: taintedrepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

# Install Default Softwares            # To be able to read dvd on your computer
- name: Install LibDVDcss Packages
  ansible.builtin.dnf:
    name:
       - libdvdcss
    state: present
    disable_gpg_check: true
  tags:
    - libdvdcss

# Remove RPM Fusion Tainted Repository
- name: Verify if RPM Fusion Tainted Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-tainted.repo
  register: taintedrepo
  tags:
    - libdvdcss

- name: Remove RPM Fusion Tainted Repository
  ansible.builtin.file:
    path: /etc/yum.repos.d/rpmfusion-nonfree-tainted.repo
    state: absent
  when: taintedrepo.stat.exists == True
  tags:
    - libdvdcss
