---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC BY 3.0. All rights reserved.
#
#
# Role libdvdcss
#
# Install Tainted Repository
# Add Repository RPM Fusion Free Tainted only to install libdvdcss
- name: Verify if RPM Fusion Free Tainted Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free-tainted.repo
  register: freetaintedrepo
  tags:
    - libdvdcss
    - basicinst

# Add Repository RPM Fusion Non-Free Tainted only to install libdvdcss
- name: Verify if RPM Fusion Non-Free Tainted Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-tainted.repo
  register: nonfreetaintedrepo
  tags:
    - libdvdcss
    - basicinst

# RPM Fusion FREE Tainted Repository only to install libdvdcss
- name: Adding RPM Fusion Free Tainted Repository only to install libdvdcss
  ansible.builtin.dnf:
    name:
       - rpmfusion-free-release-tainted
    state: present
    #disable_gpg_check: true
  when: freetaintedrepo.stat.exists == False
  tags:
    - libdvdcss

# RPM Fusion Non-FREE Tainted Repository only to install libdvdcss
- name: Adding RPM Fusion Non-Free Tainted Repository only to install libdvdcss
  ansible.builtin.dnf:
    name:
       - rpmfusion-nonfree-release-tainted
    state: present
    #disable_gpg_check: true
  when: nonfreetaintedrepo.stat.exists == False
  tags:
    - libdvdcss

# Install Default Softwares            # To be able to read dvd on your computer
- name: Install LibDVDcss Packages
  ansible.builtin.dnf:
    name:
       - libdvdcss
    state: present
    disable_gpg_check: true
  tags:
    - libdvdcss

# Remove Tainted Repository
# Remove Repository RPM Fusion Free Tainted only to install libdvdcss
- name: Verify if RPM Fusion Free Tainted Repository still exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-free-tainted.repo
  register: freetaintedrepo
  tags:
    - libdvdcss
    - basicinst

# Remove Repository RPM Fusion Non-Free Tainted only to install libdvdcss
- name: Verify if RPM Fusion Non-Free Tainted Repository still exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/rpmfusion-nonfree-tainted.repo
  register: nonfreetaintedrepo
  tags:
    - libdvdcss
    - basicinst

# Remove RPM Fusion FREE Tainted Repository
- name: Removing RPM Fusion Free Tainted Repository
  ansible.builtin.dnf:
    name:
       - rpmfusion-free-release-tainted
    state: absent
    #disable_gpg_check: true
  when: freetaintedrepo.stat.exists == False
  tags:
    - libdvdcss

# Remove RPM Fusion Non-FREE Tainted Repository
- name: Removing RPM Fusion Non-Free Tainted Repository
  ansible.builtin.dnf:
    name:
       - rpmfusion-nonfree-release-tainted
    state: absent
    #disable_gpg_check: true
  when: nonfreetaintedrepo.stat.exists == False
  tags:
    - libdvdcss
