---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# license: Licensed under CC BY 3.0. All rights reserved.
#
#
# Role libdvdcss
#
# Add Repository Livna only to install libdvdcss
- name: Verify if Livna Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss
    - basicinst

- name: Adding Livna Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna
    description: Livna
    ansible.builtin.file: livna    
    baseurl: #blablabla
    mirrorlist: http://rpm.livna.org/mirrorlist
    enabled: true
    gpgcheck: true
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Adding Livna-Debug Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna-debug
    description: Livna-Debug
    ansible.builtin.file: livna    
    baseurl: #blablabla
    mirrorlist: http://rpm.livna.org/mirrorlist-debug
    enabled: yes
    gpgcheck: true
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Adding Livna-Source Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna-Source
    description: Livna-Source
    ansible.builtin.file: livna    
    baseurl: #blablabla
    mirrorlist: http://rpm.livna.org/mirrorlist-source
    enabled: true
    gpgcheck: true
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

# Install Default Softwares            # To be able to read dvd on your computer
- name: Install LibDVDcss Packages
  ansible.builtin.dnf:
    name:
       - libdvdcss
    state: present
    disable_gpg_check: true
  tags:
    - libdvdcss

# Remove Livna Repository
- name: Verify if Livna Repository exist
  ansible.builtin.stat:
    path: /etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss

- name: Remove Livna Repository
  ansible.builtin.file:
    path: /etc/yum.repos.d/livna.repo
    state: absent
  when: livnarepo.stat.exists == True
  tags:
    - libdvdcss
