---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# Role libdvdcss

# Add Repository Livna only to install libdvdcss
- name: Verify if Livna Repository exist
  stat: path=/etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss
    - basicinst

- name: Livna enable Repository only to install libdvdcss
  template: src=templates/livna.repo.tpl dest=/etc/yum.repos.d/livna.repo mode=0644 owner=root group=root
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

# Install Default Softwares            # To be able to read dvd on your computer
- name: Install Different Packages
  ansible.builtin.dnf:
    name:
       - libdvdcss
    state: present
  tags:
    - libdvdcss

# Remove Livna Repository
- name: Verify if Livna Repository exist
  stat: path=/etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss

- name: Remove Livna Repository
  file:
    path: /etc/yum.repo.d/livna.repo
    state: absent
  when: livnarepo.stat.exists == True
  tags:
    - libdvdcss  