---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# Role libdvdcss

# Add Repository Livna only to install libdvdcss
- name: Verify if Livna Repository exist
  stat: path=/etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss
    - basicinst

- name: Add Livna Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna
    description: Livna
    file: livna    
    baseurl: #blablabal
    mirrorlist: http://rpm.livna.org/mirrorlist
    enabled: yes
    gpgcheck: yes
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Add Livna-Debug Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna-debug
    description: Livna-Debug
    file: livna    
    baseurl: #blablabal
    mirrorlist: http://rpm.livna.org/mirrorlist-debug
    enabled: yes
    gpgcheck: yes
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

- name: Add Livna-Source Repository only to install libdvdcss
  ansible.builtin.yum_repository:
    name: livna
    description: Livna-Source
    file: livna    
    baseurl: #blablabal
    mirrorlist: http://rpm.livna.org/mirrorlist-source
    enabled: yes
    gpgcheck: yes
    failovermethod: roundrobin
  when: livnarepo.stat.exists == False
  tags:
    - libdvdcss
    - basicinst

# Install Default Softwares            # To be able to read dvd on your computer
- name: Install LibDVDcss Packages
  ansible.builtin.dnf:
    name:
       - libdvdcss
    state: present
    disable_gpg_check: true
  tags:
    - libdvdcss

# Remove Livna Repository
- name: Verify if Livna Repository exist
  stat: path=/etc/yum.repos.d/livna.repo
  register: livnarepo
  tags:
    - libdvdcss

- name: Remove Livna Repository
  file:
    path: /etc/yum.repos.d/livna.repo
    state: absent
  when: livnarepo.stat.exists == True
  tags:
    - libdvdcss  