---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#

# Role Basiccodec

# Add Mplayer Codecs
- name: Verify if Mplayer Codecs exist
  stat: path=/usr/share/doc/mplayer-codecs-20061022
  register: mplayercodecs
  tags:
    codecs

# Download lastest version on www.makemkv.com
- name: Downloading MPlayer Codecs
  get_url:
    url: http://www.mplayerhq.hu/MPlayer/releases/codecs/mplayer-codecs-20061022-1.x86_64.rpm
    dest: /tmp
    mode: 0644
  when: mplayercodecs.stat.exists == False
  tags:
    codecs

- name: Downloading MPlayer Extra Codecs
  get_url:
    url: http://www.mplayerhq.hu/MPlayer/releases/codecs/mplayer-codecs-extra-20061022-1.x86_64.rpm
    dest: /tmp
    mode: 0644
  when: mplayercodecs.stat.exists == False
  tags:
    codecs

- name: Install Mplayer Codecs...
  shell: rpm -ihv /tmp/mplayer-codecs*.rpm
  when: mplayercodecs.stat.exists == False
  tags:
    codecs

# Clean Mplayer Codecs
- name: Delete MPlayer Codecs File
  file:
    path: "/tmp/mplayer-codecs-20061022-1.x86_64.rpm"
    state: absent
  tags:
    codecs

# Clean Mplayer Codecs
- name: Delete MPlayer Codecs Extra File
  file:
    path: "/tmp/mplayer-codecs-extra-20061022-1.x86_64.rpm"
    state: absent
  tags:
    codecs
