---
#
# Copyright (c) 2017 Jacques-Philippe JUBENOT
# Licensed under CC BY 3.0. All rights reserved.
#
# tasks file for mitigate-my-fed

# Clean DNF
- name: Clean DNF
  command: dnf clean all
  tags:
    - mitigate

# Remove ABRT Softwares
- name: Remove ABRT*
  command: dnf -y autoremove abrt*
  tags:
    - mitigate

# Remove LibVirt Softwares
- name: Remove LibVirt*
  command: dnf -y autoremove libvrt*
  tags:
    - mitigate

# Remove Gnome-Boxes Softwares
- name: Remove Gnome-Boxes
  command: dnf -y autoremove gnome-boxes
  tags:
    - mitigate

# Remove Gnome-Software Softwares
- name: Remove Gnome-Software
  command: dnf -y autoremove gnome-software
  tags:
    - mitigate
